server:
  port: 8080
  servlet:
    context-path: /api


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/water_db"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  spring:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

